[package]
name = "hello-rust"
version = "0.1.0"
authors = ["이상찬 / CXT / iOS <sangchan.lee@yanolja.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
